# Generated by Django 5.0.6 on 2024-12-07 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("found_location", models.CharField(max_length=255)),
                ("found_date", models.DateField()),
                ("photo", models.ImageField(upload_to="found_children_photos/")),
                ("contact_details", models.TextField()),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("children_found", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MissingChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_seen_location", models.CharField(max_length=255)),
                ("last_seen_date", models.DateField()),
                ("contact_details", models.TextField()),
                ("photo", models.ImageField(upload_to="missing_children_photos/")),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
