# Generated by Django 5.0.6 on 2024-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safenestapp", "0002_matchedchild_foundchild_name_foundchild_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingchild",
            name="status",
            field=models.CharField(
                choices=[("Missing", "Missing"), ("Matched", "Matched")],
                default="Missing",
                max_length=10,
            ),
        ),
    ]
