# Generated by Django 5.0.6 on 2024-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safenestapp", "0003_missingchild_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingchild",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("Found", "Found"),
                    ("Closed", "Closed"),
                ],
                default="Missing",
                max_length=12,
            ),
        ),
    ]
