# Generated by Django 5.0.6 on 2024-12-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safenestapp", "0004_alter_missingchild_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingchild",
            name="matched_frames",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="missingchild",
            name="matched_photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="missingchild",
            name="matched_videos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
